# Sequence # 6
# Description: This workflow builds the application and uploads the build artifacts for deployment.
name: Environment Variable Definition

on:
  push:
    branches:
      - himTech
  workflow_dispatch:

# Define environment variables at the workflow level
env:
  APP_ENV: production
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  build-appln:
    runs-on: ubuntu-latest
    # Define environment variables at the job level
    env:
        BUILD_ENV: $APP_ENV
        DB_NAME: my_database
        DB_USER: admin
    steps:
      - name: Checkout application repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.5'
          cache-read-only: false

      - name: Change gradle permission
        run: chmod +x ./gradlew

      - name: Run Gradle Build
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            build/libs/*.jar
            build/resources/main/application.properties
      - name: Display environment variables
        run: |
          echo "APP_ENV is $APP_ENV"
          echo "BUILD_ENV is $BUILD_ENV"
          echo "DB_NAME is $DB_NAME"
          echo "DB_USER is $DB_USER"
          echo "API_KEY is $API_KEY"
# To access environment variable, the format ${{ env.APP_ENV }} can also be used in the above step

  deploy:
    needs: build-appln
    runs-on: ubuntu-latest

    steps:
      - name: Get build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: List downloaded files
        run: ls -laR

      - name: Deploy the build
        run: echo "Deploying build on multiple clouds"
      - name: Display environment variables in deploy job
        run: |
          echo "APP_ENV is $APP_ENV"
          echo "API_KEY is $API_KEY"
          echo "BUILD_ENV is $BUILD_ENV"
          echo "DB_NAME is $DB_NAME"
          echo "DB_USER is $DB_USER"
# This will print only APP_ENV and API_KEY as they are defined at the workflow level.
# BUILD_ENV, DB_NAME, and DB_USER are not accessible here as they are defined at the job level in the build-appln job.