# Sequence # 4
# Description: This workflow builds the application and read the generated jarfile name.
name: Application build and upload artifact

on:
  push:
    branches:
      - main

jobs:
  build-appln:
    runs-on: ubuntu-latest
    outputs:
      jar_file: ${{ steps.read_jar.outputs.jar_file }}
    steps:
      - name: Checkout application repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.5'
          cache-read-only: false

      - name: Change gradle permission
        run: chmod +x ./gradlew

      - name: Run Gradle Build
        run: ./gradlew build

      - name: Read generated jar file name
        id: read_jar
        run: |
          JAR_FILE=$(find build/libs/*-SNAPSHOT.jar -type f -execdir echo '{}')
          echo "Generated JAR file: $JAR_FILE"
          echo "jar_file=$JAR_FILE" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            build/libs/*.jar
            build/resources/main/application.properties

  deploy:
    needs: build-appln
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: List downloaded files
        run: ls -laR

      - name: Show jar file name
        run: echo "Jar file name is ${{ needs.build-appln.outputs.jar_file }}"

      - name: Deploy the build
        run: echo "Deploying build on multiple clouds"
