# Sequence # 12 : Calling of Reusable Workflow

name: Using of Reusable Workflow

on:
  push:
    branches:
      - himtech
  workflow_dispatch:

jobs:
  build-appln:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.5'
          cache-read-only: false

      - name: Change gradle permission
        run: chmod +x ./gradlew

      - name: Run Gradle Build
        run: ./gradlew build

    # Upload build artifacts to Github space
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: appln-artifact
          path: build/libs/*-SNAPSHOT.jar

  deploy-appln:
    needs: build-appln
    # Calling the reusable workflow defined in .github/workflows/reusable-workflow.yml
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      artifact-name: 'appln-artifact'

#  Print the deployment status returned by the reusable workflow
  print-status:
    needs: deploy-appln
    runs-on: ubuntu-latest
    steps:
      - name: Print Deployment Status
        run: ${{ needs.deploy-appln.outputs.deployment-status }}
